<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua nova senha</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form>
              <div class="form-group">
                <input type="password" id="newPass" name="senha" class="form-control" placeholder="Senha">
                <input type="hidden" name="email" value="<?= $_GET['email'] ?>">
                <input type="hidden" name="token" value="<?= $_GET['token'] ?>">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao enviar, você estará redefinindo sua nova senha.
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Enviar</button>  
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(() => {
    $('button').on('click', e => {
      e.preventDefault()
      var password = $('#newPass')

      if (password.val() != "") {

        let dados = $('form').serialize()

        $.ajax({
          type: 'post',
          url: '/set_new_pass',
          data: dados,
          success: function (response) {
            alert(response)
            window.location = '/'
          }
        })
      }else {
        alert('Campo vazio:')
      }
    })
  })
</script>



    
  