<div class="container-fluid h-100">
	<div class="row">

		<div id="formEmail" class="modal fade">
    	<div class="modal-dialog">
      	<div class="modal-content">
        	<div class="modal-header">
          	<h2 class="modal-title">Digite seu E-mail</h2>
          </div>

          <div class="modal-body">
            <input type="text" class="form-control" placeholder="Email" id="userEmail"><br>
        	</div>

          <div class="modal-footer">
            <input type="button" onclick="recuperarEmail()"  value="Enviar" class="btn btn-success">
          </div>
        </div>
      </div>
		</div>
		
		<div id="loadin" class="modal fade">
    	<div class="modal-dialog">
      	<div class="modal-content">
					<div class="text-center">
						<div class="spinner-border text-primary m-5" style="width: 4rem; height: 4rem;" role="status">
							<span class="sr-only">Loading...</span>
						</div>
					</div>
        </div>
      </div>
    </div>
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
					<div class="communicationItem">
						<i class="fas fa-search fa-2x mr-3"></i>
						Siga o que lhe interessa.
					</div>
					<div class="communicationItem">
						<i class="fas fa-user-friends fa-2x mr-3"></i>
						Saiba sobre o que as pessoas estão falando.
					</div>
					<div class="communicationItem">
						<i class="far fa-comment fa-2x mr-3"></i>
						Participe da conversa.
					</div>
				</div>
			</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
			<form method="post" action="/autenticar">
				<div class="row">
					<div class="col">
						<input type="text" name="email" class="form-control" placeholder="E-mail">
					</div>
					<div class="col">
						<input type="password" name="senha" class="form-control" placeholder="Senha">
					</div>
					<div class="col-auto">
						<button type="submit" class="btn btn-primary mb-2">Entrar</button>
					</div>
				</div>
				<?php if($this->view->login == 'erro') { ?>
					<div class="row">
						<div class="col">
							<span class="text text-danger">E-mail e ou senha inválido(s)</span>
						</div>
					</div>
				<?php } ?>
			</form>

			<div class="row pt-5 pl-5 pr-5">
				<div class="col pl-5 pr-5">
					<img src="/img/twitter_logo.png" />
					<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

					<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
					<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
					<button class="btn btn-primary btn-block mb-2" id="forgtButton">Esqueci a senha</button>
				</div>	
			</div>
    </div>
  </div>
</div>

<script>
	$(document).ready(() => {
		$('#forgtButton').on('click', e => {
			$('#formEmail').modal('show')
		})
	})

	function recuperarEmail() {
		var email = $('#userEmail')
		if (email.val() != "") {
			
			$('#formEmail').modal('hide');
			$('#loadin').modal('show')

			$.ajax({
				type: 'post',
				url: '/forgot_password',
				data: {
					email: email.val()
				},
				success: function (response) {
					$('#loadin').modal('hide')
					setTimeout(() => {alert(response)}, 1000)
					setTimeout(() => {location.reload()}, 2000)
					
				},
				error: function (response) {
					alert(response)
					$('#loadin').modal('hide')
					location.reload()
				}
			})
		}
		else {
			alert('Campo vazio')
		}
	}
</script>